### ISSUE TITLE
New connection format

### ISSUE THREAD

**Issue by zix99** [dstiert/netgun#3]
There should be some helper text in the "New connection" window so I know what format to post the connection strings in (And what formats are acceptable).

**Comment by kstiert** [comment]
Would text referring to the "Standard Connection String Format" be sufficient? Should I include the link or more info?

http://docs.mongodb.org/manual/reference/connection-string/

**Comment by zix99** [comment]
Yeah. I'd just make a label box above the textbox with the text:

```
mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]
```

So I don't have to do to a different webpage to find it.
